import {
  calculateTargetBudget,
  extractNonNegotiablesAndAssumptions,
  verifyRadicalTransformation,
  selectFailureOperators,
} from '../src/utils/radicalTransformation';
import { saturateToCharacterBudget } from '../src/utils/characterBudget';
import { generateDavidAlgorithmicSynthesis } from '../lib/david';

async function runJob1TestSuite() {
  console.log('====================================================');
  console.log('STARTING JOB 1 VERIFICATION TEST SUITE (TESTS A - F)');
  console.log('====================================================\n');

  let allPassed = true;

  // ----------------------------------------------------
  // TEST A: Short input, large budget (OpenArt: 3,200 max)
  // ----------------------------------------------------
  console.log('--- TEST A: Short Input, Large Budget ---');
  const shortInput = 'A quiet stone well in an ancient courtyard';
  const synthA = generateDavidAlgorithmicSynthesis({
    concept: shortInput,
    target: 'openart',
    targetLength: 3200,
    entropyLevel: 8,
  });

  const promptA = synthA.slop.prompt;
  const budgetA = calculateTargetBudget(3200);
  const analysisA = extractNonNegotiablesAndAssumptions(shortInput);
  const verificationA = verifyRadicalTransformation(shortInput, promptA, budgetA, analysisA);

  console.log(`Input Length: ${shortInput.length} chars`);
  console.log(`Output Length: ${promptA.length} chars`);
  console.log(`Budget Range Target: ${budgetA.minimumTarget} - ${budgetA.upperTarget} chars`);
  console.log(`Utilization: ${verificationA.budgetUtilizationPercent}%`);
  console.log(`Preserved Anchors Found:`, verificationA.preservedAnchorsFound);
  console.log(`Mutations Detected: ${verificationA.mutationsDetectedCount}`);
  console.log(`Result Passed: ${verificationA.passed ? 'YES' : 'NO'}`);
  console.log(`Summary: ${verificationA.verdictSummary}\n`);

  if (!verificationA.passed) allPassed = false;

  // ----------------------------------------------------
  // TEST B: Long input (2,500 chars), large budget (3,200 chars)
  // ----------------------------------------------------
  console.log('--- TEST B: Long Input, Large Budget ---');
  const longInput = `The deep subterranean observatory was established in 1842 by an obscure royal astronomical society whose members believed the stars could be seen more clearly through two miles of solid granite. They constructed a vertical optical cylinder lined with mirrors ground from volcanic obsidian and mounted in cast-iron gimbals thirty feet across. Water continuously seeped through the fissures in the surrounding bedrock, creating a persistent mineral mist that settled over the brass micrometers and frosted the counterweights with deposits of pale green malachite. At the base of the shaft sat the primary azimuth mount, driven by an escapement clock whose lead pendulum weighed three tons and swung through an arc measured in inches. Four observers sat in leather slings suspended above the central aperture, logging the transit times of occulted stellar bodies into heavy vellum ledgers bound in oilcloth. They communicated with the surface only by pneumatic message tubes that produced a sharp metallic hiss when pressurized. Over eighty years of continuous operation, the mirrors slowly oxidized, their dark glassy faces acquiring an iridescent film that distorted incoming stellar light into complex interference rings. Rather than abandon the installation, the resident astronomers embraced the optical aberrations, treating the distorted diffraction spikes as genuine cosmological structures. They re-calibrated their catalog to classify nebulae by their chromatic fringing and documented thousands of hypothetical binary systems visible only through the degraded obsidian planes. The subterranean climate was perpetually cold and saturated with ozone generated by static discharges from the rotating clockwork gears. Deep underground, away from sunlight and seasonal changes, the observers developed their own temporal reckoning based on the subterranean resonance of lunar tidal stresses flexing the surrounding granite walls. Every six hours, the rock strata groaned with microscopic shear fractures, echoing through the optical shaft like distant thunder.`;
  
  const synthB = generateDavidAlgorithmicSynthesis({
    concept: longInput,
    target: 'openart',
    targetLength: 3200,
    entropyLevel: 7,
  });

  const promptB = synthB.slop.prompt;
  const budgetB = calculateTargetBudget(3200);
  const analysisB = extractNonNegotiablesAndAssumptions(longInput);
  const verificationB = verifyRadicalTransformation(longInput, promptB, budgetB, analysisB);

  console.log(`Input Length: ${longInput.length} chars`);
  console.log(`Output Length: ${promptB.length} chars`);
  console.log(`Output >= Input Length: ${promptB.length >= longInput.length ? 'YES' : 'NO'}`);
  console.log(`Utilization: ${verificationB.budgetUtilizationPercent}%`);
  console.log(`Result Passed: ${verificationB.passed ? 'YES' : 'NO'}`);
  console.log(`Summary: ${verificationB.verdictSummary}\n`);

  if (!verificationB.passed || promptB.length < longInput.length * 0.9) allPassed = false;

  // ----------------------------------------------------
  // TEST C: Detailed Prompt, Assumption Dismantling
  // ----------------------------------------------------
  console.log('--- TEST C: Detailed Prompt & Structural Dismantling ---');
  const detailedInput = 'A clockwork owl perching on a Victorian lamppost during a London snowfall at midnight';
  const synthC = generateDavidAlgorithmicSynthesis({
    concept: detailedInput,
    target: 'midjourney_flux',
    targetLength: 1900,
    entropyLevel: 8,
  });

  const promptC = synthC.slop.prompt;
  const budgetC = calculateTargetBudget(1900);
  const analysisC = extractNonNegotiablesAndAssumptions(detailedInput);
  const verificationC = verifyRadicalTransformation(detailedInput, promptC, budgetC, analysisC);

  console.log(`Input: "${detailedInput}"`);
  console.log(`Identified Hidden Assumptions:`, analysisC.hiddenAssumptions);
  console.log(`Output Length: ${promptC.length} chars`);
  console.log(`Target Range: ${budgetC.minimumTarget} - ${budgetC.upperTarget} chars`);
  console.log(`Utilization: ${verificationC.budgetUtilizationPercent}%`);
  console.log(`Mutations Active: ${verificationC.mutationsDetectedCount}`);
  console.log(`Result Passed: ${verificationC.passed ? 'YES' : 'NO'}`);
  console.log(`Summary: ${verificationC.verdictSummary}\n`);

  if (!verificationC.passed) allPassed = false;

  // ----------------------------------------------------
  // TEST D: Critical Reference & Identity Preservation
  // ----------------------------------------------------
  console.log('--- TEST D: Critical Reference / Identity Preservation ---');
  const identityInput = 'A cinematic character portrait of @merry holding the relic "Aethelgard Core" in Neo-Shinjuku';
  const synthD = generateDavidAlgorithmicSynthesis({
    concept: identityInput,
    target: 'grok',
    targetLength: 1900,
    entropyLevel: 9,
  });

  const promptD = synthD.slop.prompt;
  const budgetD = calculateTargetBudget(1900);
  const analysisD = extractNonNegotiablesAndAssumptions(identityInput);
  const verificationD = verifyRadicalTransformation(identityInput, promptD, budgetD, analysisD);

  console.log(`Input Identity Tokens:`, analysisD.preservedAnchors);
  console.log(`Preserved Anchors in Output:`, verificationD.preservedAnchorsFound);
  console.log(`Preserved Invariants Intact: ${verificationD.preservedAnchorsIntact ? 'YES' : 'NO'}`);
  console.log(`Output Length: ${promptD.length} chars (${verificationD.budgetUtilizationPercent}%)`);
  console.log(`Result Passed: ${verificationD.passed ? 'YES' : 'NO'}`);
  console.log(`Summary: ${verificationD.verdictSummary}\n`);

  if (!verificationD.passed || !verificationD.preservedAnchorsIntact) allPassed = false;

  // ----------------------------------------------------
  // TEST E: Strict Short Target (Grok Image: 1,900 chars)
  // ----------------------------------------------------
  console.log('--- TEST E: Strict Target Ceiling Enforcement ---');
  const strictInput = 'Submerged cathedral ruins enveloped in bioluminescent siphonophores';
  const synthE = generateDavidAlgorithmicSynthesis({
    concept: strictInput,
    target: 'grok',
    targetLength: 1900,
    entropyLevel: 7,
  });

  const promptE = synthE.slop.prompt;
  const budgetE = calculateTargetBudget(1900);
  const analysisE = extractNonNegotiablesAndAssumptions(strictInput);
  const verificationE = verifyRadicalTransformation(strictInput, promptE, budgetE, analysisE);

  console.log(`Target Cap: 1,900 chars`);
  console.log(`Output Length: ${promptE.length} chars`);
  console.log(`Within 90-95% of 1,900 (1710 - 1900): ${promptE.length >= 1710 && promptE.length <= 1900 ? 'YES' : 'NO'}`);
  console.log(`Utilization: ${verificationE.budgetUtilizationPercent}%`);
  console.log(`Result Passed: ${verificationE.passed ? 'YES' : 'NO'}`);
  console.log(`Summary: ${verificationE.verdictSummary}\n`);

  if (!verificationE.passed) allPassed = false;

  // ----------------------------------------------------
  // TEST F: Source vs Output Structural Mutation Check
  // ----------------------------------------------------
  console.log('--- TEST F: Source vs Output Structural Mutation Verification ---');
  const promptF = synthA.slop.prompt;
  const isRadical = verificationA.isRadicalTransformation && promptF !== shortInput;
  console.log(`Source Prompt: "${shortInput}"`);
  console.log(`Is Radical Transformation: ${isRadical ? 'YES' : 'NO'}`);
  console.log(`Structural Mutation Mechanics Count: ${verificationA.mutationsDetectedCount}`);
  console.log(`Verifiable Anchor Retention: [${verificationA.preservedAnchorsFound.join(', ')}]`);
  console.log(`Not a mere cosmetic polish: ${isRadical ? 'CONFIRMED' : 'FAILED'}\n`);

  if (!isRadical) allPassed = false;

  console.log('====================================================');
  console.log(`OVERALL JOB 1 TEST SUITE RESULT: ${allPassed ? 'ALL TESTS PASSED' : 'TESTS FAILED'}`);
  console.log('====================================================');

  if (!allPassed) {
    process.exit(1);
  }
}

runJob1TestSuite().catch((err) => {
  console.error('Test execution failed:', err);
  process.exit(1);
});
